spring:
  application:
    name: Consumer
  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: com.KafkaDemo.Consumer.Package
    binder:
      brokers: localhost:9092
  cloud:
    function:
      definition: processPackage;processPackageStatus
    stream:
      function:
        definition: processPackage;processPackageStatus
      bindings:
        processPackage-in-0:
          destination: config-topic
          group: package-info
        processPackageStatus-in-0:
          destination: config-topic2
          group: package-status
server:
  port: 8081
